# Generated by Django 6.0.2 on 2026-02-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_Alex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
