# Generated by Django 6.0.2 on 2026-02-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_Alex', '0002_empleado_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoSubido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
